export const styles = {
    wrapper: "relative flex w-full flex-col",
    section: "relative w-full",
    fullScreen: "h-screen",
    mainGrid: "absolute top-1/3 left-1/2 z-[2] max-w-[80vw] -translate-x-1/2 -translate-y-1/2 text-left md:max-w-[80vw] flex lg:flex-row-reverse md:flex-row-reverse justify-center p-5",
    mainGridReverse: "absolute top-1/2 left-1/2 z-[2] max-w-[80vw] -translate-x-1/2 -translate-y-1/2 text-left md:max-w-[80vw] flex lg:flex-row md:flex-row-reverse sm:flex-col xs:flex-col justify-center p-5",
    mainDesctiption: "flex justify-center",
    mainImageGrid: "flex justify-center",
    mainImage: "flex justify-center",
    mainGridTitle: "relative bottom-0 text-left mb-5 animate-titleAnim font-montserrat font-black lg:text-5xl uppercase tracking-wider text-white delay-[0s] md:text-4xl sm:text-[32px] xs:text-[20px]",
    mainGridText: "relative bottom-0 mb-6 animate-titleAnim text-left font-montserrat font-medium text-lg delay-200 sm:text-md md:mb-10 md:text-[20px] w-[42em] text-white",
    heading: "text-white flex flex-row",
    buttonsGrid: "flex flex-row border border-beraBlue p-5 rounded-[5px] justify-around lg:ml-3",
    buttons: "relative bottom-0 min-w-[90px] animate-titleAnim font-montserrat font-bold text-md capitalize text-white delay-[400ms] max-md:float-none max-md:m-0 max-md:w-full rounded-[5px]",
    miniSection: "absolute bottom-[10em] w-full",
    miniSectionContainer: "flex flex-row md:flex-row sm:flex-col xs:flex-col",
    socialMediaGrid: "flex justify-center gap-2 pl-[50px]",
    socialMediaIcon: "flex px-1 cursor-pointer",
    scrollbuttonGrid: "flex justify-center",
    scrollbutton: "py-auto my-auto bg-beraPurple p-4 w-[60px] h-[60px] rounded-[50%] flex justify-center",
    arrowDown: "text-white text-[30px]",
    statistics: "relative top-[32px] w-full h-[22vh]",
    text: "flex justify-end  animate-titleAnim font-montserrat font-medium delay-200 text-right p-5 lg:justify-end md:justify-center sm:justify-center xs:justify-center text-white",
    underline: "underline underline-offset-[5px] decoration-beraPurple decoration-4",
    statisticsGrid: "bg-[#181346] h-full rounded-l-[10px] rounded-r-[10px] flex flex-row justify-around",
    statisticsGridItem: "text-center p-5",
    statisticsGridItemNumber: "font-montserrat font-bold",
    statisticsGridItemName: "text-beraPurple",
    footer: "relative bg-[#181346] w-full h-[25vh]",
    footerSection: "flex flex-col gap-2 absolute top-[60px] left-[230px] leading-6",
    external: "flex flex-col justify-start relative",
}